version: '3'
services:
  database:
    image: mysql:latest
    container_name: mysql_flask
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api_flask  
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - flask_environment
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - flask_environment
    volumes:
      - .:/backend
    depends_on:
      - database
    env_file:
      - .env
volumes:
  dbdata:
networks:
  flask_environment: